### ISSUE TITLE
Except GSM100, other datasets are evaluated in 0-shot?

### ISSUE THREAD

**Issue by zhimin-z** [OpenLMLab/LEval#10]
I hope to confirm the [leaderboard](https://l-eval.github.io/) configuration.

**Comment by ChenxinAn-fdu** [comment]
Yes, we did not add examples for other tasks. We suggest modifying based on our inference code under the `Baselines` folder.  The leaderboard [leaderboard](https://l-eval.github.io/)  has not been updated please refer to our [paper](https://arxiv.org/abs/2307.11088) for the up-to-date results!
