### ISSUE TITLE
Where is the open-ened tasks datasets used for GPT-4/GPT-3.5 evalutation

### ISSUE THREAD

**Issue by altctrl00** [OpenLMLab/LEval#12]
Hi, I wonder where is  the "96-question" and "85+96 question" mentioned in Table 4 of your paper?

**Comment by altctrl00** [comment]
Is it in the LEval-data/Open-ended-tasks and the "evaluation" key is "LLM"?

**Comment by ChenxinAn-fdu** [comment]
Yes!
