### ISSUE TITLE
Is GSM100 evaluated using 8-shot or 16-shot?

### ISSUE THREAD

**Issue by zhimin-z** [OpenLMLab/LEval#9]
![image](https://github.com/OpenLMLab/LEval/assets/8592144/b6716885-3fe5-49bd-8f51-19eb4971e596)
![image](https://github.com/OpenLMLab/LEval/assets/8592144/60dc1d52-a674-4dc7-9224-265e64422a2c)

**Comment by ChenxinAn-fdu** [comment]
Hi zhimin! Thank you for the question. GSM100 uses 16 examples where *8 of these examples* are token from chain-of-thought-hub and the *remaining 8 examples* are written by us.  We verify our 8 examples on turbo-16k results show that using more examples improves turbo from 80 -> 84.
